//===========================================================================
//機能：指定された契約ＩＤのデータを抽出する
//ＤＢ接続先をCHECKに変更したバージョン
//
//作成日：2007.11.9
//作成者：前田
//更新履歴
//Ｖ３追加 2009/03/13 s.maeda
//===========================================================================
//define("HOST","KMDB1");
//define("DBNAME","kcsmotion");
//パラメータチェック
//数が正しくない
//DBのwebパスワード
//DBのpostgresパスワード
//データ抽出用ＳＱＬ
//データ削除用ＳＱＬ
//ファイルオープン
//クライアント文字コード設定ファイル出力
//データ削除用ＳＱＬ
//ＤＢ接続
//クライアント文字コード設定
//Web のホームディレクトリに.pgpass を作成する
//データ抽出
//.pgpass を削除する
//バッファ出力
//ファイルクローズ
error_reporting(E_ALL);
const HOST = "KMCHKDB";
const DBNAME = "check-kcsmotion";
const SCRIPTNAME = "pactdata_exp_check.php";
const TEMPFILE = "/kcs/script/batch/tmp.dat";

if (_SERVER.argv.length != 2) //数が正しい
	{
		usage("");
	} else //契約ＩＤチェック
	{
		if (ereg("^[0-9]+$", _SERVER.argv[1]) == false) {
			usage("");
		} else {
			const PACTID = _SERVER.argv[1];
		}
	}

var dbPassW = file_get_contents("/kcs/conf/dbpassw").trim();
var dbPassP = file_get_contents("/kcs/conf/dbpassp").trim();
var H_select = {
	pact_tb: "",
	post_tb: "",
	post_01_tb: "",
	post_02_tb: "",
	post_03_tb: "",
	post_04_tb: "",
	post_05_tb: "",
	post_06_tb: "",
	post_07_tb: "",
	post_08_tb: "",
	post_09_tb: "",
	post_10_tb: "",
	post_11_tb: "",
	post_12_tb: "",
	post_13_tb: "",
	post_14_tb: "",
	post_15_tb: "",
	post_16_tb: "",
	post_17_tb: "",
	post_18_tb: "",
	post_19_tb: "",
	post_20_tb: "",
	post_21_tb: "",
	post_22_tb: "",
	post_23_tb: "",
	post_24_tb: "",
	post_deleted_tb: "",
	post_relation_tb: "",
	post_relation_01_tb: "",
	post_relation_02_tb: "",
	post_relation_03_tb: "",
	post_relation_04_tb: "",
	post_relation_05_tb: "",
	post_relation_06_tb: "",
	post_relation_07_tb: "",
	post_relation_08_tb: "",
	post_relation_09_tb: "",
	post_relation_10_tb: "",
	post_relation_11_tb: "",
	post_relation_12_tb: "",
	post_relation_13_tb: "",
	post_relation_14_tb: "",
	post_relation_15_tb: "",
	post_relation_16_tb: "",
	post_relation_17_tb: "",
	post_relation_18_tb: "",
	post_relation_19_tb: "",
	post_relation_20_tb: "",
	post_relation_21_tb: "",
	post_relation_22_tb: "",
	post_relation_23_tb: "",
	post_relation_24_tb: "",
	post_relation_deleted_tb: "",
	user_tb: "",
	user_deleted_tb: "",
	tel_tb: "",
	tel_01_tb: "",
	tel_02_tb: "",
	tel_03_tb: "",
	tel_04_tb: "",
	tel_05_tb: "",
	tel_06_tb: "",
	tel_07_tb: "",
	tel_08_tb: "",
	tel_09_tb: "",
	tel_10_tb: "",
	tel_11_tb: "",
	tel_12_tb: "",
	tel_13_tb: "",
	tel_14_tb: "",
	tel_15_tb: "",
	tel_16_tb: "",
	tel_17_tb: "",
	tel_18_tb: "",
	tel_19_tb: "",
	tel_20_tb: "",
	tel_21_tb: "",
	tel_22_tb: "",
	tel_23_tb: "",
	tel_24_tb: "",
	tel_deleted_tb: "",
	asp_charge_tb: "",
	bill_01_tb: "",
	bill_02_tb: "",
	bill_03_tb: "",
	bill_04_tb: "",
	bill_05_tb: "",
	bill_06_tb: "",
	bill_07_tb: "",
	bill_08_tb: "",
	bill_09_tb: "",
	bill_10_tb: "",
	bill_11_tb: "",
	bill_12_tb: "",
	bill_13_tb: "",
	bill_14_tb: "",
	bill_15_tb: "",
	bill_16_tb: "",
	bill_17_tb: "",
	bill_18_tb: "",
	bill_19_tb: "",
	bill_20_tb: "",
	bill_21_tb: "",
	bill_22_tb: "",
	bill_23_tb: "",
	bill_24_tb: "",
	bill_custom_tb: "",
	bill_history_tb: "",
	bill_prtel_tb: "",
	clamp_tb: "",
	clampfile_tb: "",
	clamptemp_tb: "",
	clampdb_error_tb: "",
	clampdb_index_tb: "",
	clampdb_type_tb: "",
	clampdb_ready_tb: "",
	commhistory_01_tb: "",
	commhistory_02_tb: "",
	commhistory_03_tb: "",
	commhistory_04_tb: "",
	commhistory_05_tb: "",
	commhistory_06_tb: "",
	commhistory_07_tb: "",
	commhistory_08_tb: "",
	commhistory_09_tb: "",
	commhistory_10_tb: "",
	commhistory_11_tb: "",
	commhistory_12_tb: "",
	disratio_tb: "",
	dl_property_tb: "",
	dummy_tel_tb: "",
	fnc_relation_tb: "",
	infohistory_01_tb: "",
	infohistory_02_tb: "",
	infohistory_03_tb: "",
	infohistory_04_tb: "",
	infohistory_05_tb: "",
	infohistory_06_tb: "",
	infohistory_07_tb: "",
	infohistory_08_tb: "",
	infohistory_09_tb: "",
	infohistory_10_tb: "",
	infohistory_11_tb: "",
	infohistory_12_tb: "",
	ip_restrict_tb: "",
	joker_log_tb: "",
	kamoku_tb: "",
	kamoku_rel_utiwake_tb: "",
	kousi_bill_01_tb: "",
	kousi_bill_02_tb: "",
	kousi_bill_03_tb: "",
	kousi_bill_04_tb: "",
	kousi_bill_05_tb: "",
	kousi_bill_06_tb: "",
	kousi_bill_07_tb: "",
	kousi_bill_08_tb: "",
	kousi_bill_09_tb: "",
	kousi_bill_10_tb: "",
	kousi_bill_11_tb: "",
	kousi_bill_12_tb: "",
	kousi_bill_13_tb: "",
	kousi_bill_14_tb: "",
	kousi_bill_15_tb: "",
	kousi_bill_16_tb: "",
	kousi_bill_17_tb: "",
	kousi_bill_18_tb: "",
	kousi_bill_19_tb: "",
	kousi_bill_20_tb: "",
	kousi_bill_21_tb: "",
	kousi_bill_22_tb: "",
	kousi_bill_23_tb: "",
	kousi_bill_24_tb: "",
	kousi_default_tb: "",
	kousi_fromtel_master_tb: "",
	kousi_rel_pact_tb: "",
	kousi_tel_bill_01_tb: "",
	kousi_tel_bill_02_tb: "",
	kousi_tel_bill_03_tb: "",
	kousi_tel_bill_04_tb: "",
	kousi_tel_bill_05_tb: "",
	kousi_tel_bill_06_tb: "",
	kousi_tel_bill_07_tb: "",
	kousi_tel_bill_08_tb: "",
	kousi_tel_bill_09_tb: "",
	kousi_tel_bill_10_tb: "",
	kousi_tel_bill_11_tb: "",
	kousi_tel_bill_12_tb: "",
	kousi_tel_bill_13_tb: "",
	kousi_tel_bill_14_tb: "",
	kousi_tel_bill_15_tb: "",
	kousi_tel_bill_16_tb: "",
	kousi_tel_bill_17_tb: "",
	kousi_tel_bill_18_tb: "",
	kousi_tel_bill_19_tb: "",
	kousi_tel_bill_20_tb: "",
	kousi_tel_bill_21_tb: "",
	kousi_tel_bill_22_tb: "",
	kousi_tel_bill_23_tb: "",
	kousi_tel_bill_24_tb: "",
	kousi_totel_master_tb: "",
	login_rel_sess_tb: "",
	mnglog_tb: "",
	pact_rel_carrier_tb: "",
	pact_rel_shop_tb: "",
	plan_history_tb: "",
	plan_predata_tb: "",
	plan_recom_tb: "",
	recent_telcnt_tb: "",
	recog_batch_tb: "",
	recognize_tb: "",
	secure_charge_tb: "",
	secure_history_tb: "",
	secure_pact_tb: "",
	secure_reserve_tb: "",
	secure_tb: "",
	shop_relation_tb: "",
	sim_config_tb: "",
	sim_log_tb: "",
	sim_top_telno_01_tb: "",
	sim_top_telno_02_tb: "",
	sim_top_telno_03_tb: "",
	sim_top_telno_04_tb: "",
	sim_top_telno_05_tb: "",
	sim_top_telno_06_tb: "",
	sim_top_telno_07_tb: "",
	sim_top_telno_08_tb: "",
	sim_top_telno_09_tb: "",
	sim_top_telno_10_tb: "",
	sim_top_telno_11_tb: "",
	sim_top_telno_12_tb: "",
	sim_trend_01_tb: "",
	sim_trend_02_tb: "",
	sim_trend_03_tb: "",
	sim_trend_04_tb: "",
	sim_trend_05_tb: "",
	sim_trend_06_tb: "",
	sim_trend_07_tb: "",
	sim_trend_08_tb: "",
	sim_trend_09_tb: "",
	sim_trend_10_tb: "",
	sim_trend_11_tb: "",
	sim_trend_12_tb: "",
	sim_trend_13_tb: "",
	sim_trend_14_tb: "",
	sim_trend_15_tb: "",
	sim_trend_16_tb: "",
	sim_trend_17_tb: "",
	sim_trend_18_tb: "",
	sim_trend_19_tb: "",
	sim_trend_20_tb: "",
	sim_trend_21_tb: "",
	sim_trend_22_tb: "",
	sim_trend_23_tb: "",
	sim_trend_24_tb: "",
	sshx_a1_tb: "",
	sshx_a2_tb: "",
	sshx_b1_tb: "",
	sshx_b2_tb: "",
	sshx_b3_tb: "",
	sshx_b4_tb: "",
	sshx_c1_tb: "",
	sshx_c2_tb: "",
	sshx_c3_tb: "",
	sshx_c4_tb: "",
	sshx_d1_tb: "",
	sshx_d2_tb: "",
	sshx_d3_tb: "",
	sshx_d4_tb: "",
	sshx_d5_tb: "",
	sshx_e1_tb: "",
	sshx_inpmark_tb: "",
	sshx_j1_tb: "",
	sshx_j2_tb: "",
	sshx_j3_tb: "",
	sshx_j4_tb: "",
	sshx_tel_01_bkup: "",
	sshx_tel_02_bkup: "",
	sshx_tel_03_bkup: "",
	sshx_tel_04_bkup: "",
	sshx_tel_05_bkup: "",
	sshx_tel_06_bkup: "",
	sshx_tel_07_bkup: "",
	sshx_tel_08_bkup: "",
	sshx_tel_09_bkup: "",
	sshx_tel_10_bkup: "",
	sshx_tel_11_bkup: "",
	sshx_tel_12_bkup: "",
	sshx_tel_13_bkup: "",
	sshx_tel_14_bkup: "",
	sshx_tel_15_bkup: "",
	sshx_tel_16_bkup: "",
	sshx_tel_17_bkup: "",
	sshx_tel_18_bkup: "",
	sshx_tel_19_bkup: "",
	sshx_tel_20_bkup: "",
	sshx_tel_21_bkup: "",
	sshx_tel_22_bkup: "",
	sshx_tel_23_bkup: "",
	sshx_tel_24_bkup: "",
	sshx_zzz_01_tb: "",
	sshx_zzz_02_tb: "",
	sshx_zzz_03_tb: "",
	sshx_zzz_04_tb: "",
	sshx_zzz_05_tb: "",
	sshx_zzz_06_tb: "",
	sshx_zzz_07_tb: "",
	sshx_zzz_08_tb: "",
	sshx_zzz_09_tb: "",
	sshx_zzz_10_tb: "",
	sshx_zzz_11_tb: "",
	sshx_zzz_12_tb: "",
	sshx_zzz_13_tb: "",
	sshx_zzz_14_tb: "",
	sshx_zzz_15_tb: "",
	sshx_zzz_16_tb: "",
	sshx_zzz_17_tb: "",
	sshx_zzz_18_tb: "",
	sshx_zzz_19_tb: "",
	sshx_zzz_20_tb: "",
	sshx_zzz_21_tb: "",
	sshx_zzz_22_tb: "",
	sshx_zzz_23_tb: "",
	sshx_zzz_24_tb: "",
	tel_bill_01_tb: "",
	tel_bill_02_tb: "",
	tel_bill_03_tb: "",
	tel_bill_04_tb: "",
	tel_bill_05_tb: "",
	tel_bill_06_tb: "",
	tel_bill_07_tb: "",
	tel_bill_08_tb: "",
	tel_bill_09_tb: "",
	tel_bill_10_tb: "",
	tel_bill_11_tb: "",
	tel_bill_12_tb: "",
	tel_bill_13_tb: "",
	tel_bill_14_tb: "",
	tel_bill_15_tb: "",
	tel_bill_16_tb: "",
	tel_bill_17_tb: "",
	tel_bill_18_tb: "",
	tel_bill_19_tb: "",
	tel_bill_20_tb: "",
	tel_bill_21_tb: "",
	tel_bill_22_tb: "",
	tel_bill_23_tb: "",
	tel_bill_24_tb: "",
	tel_details_01_tb: "",
	tel_details_02_tb: "",
	tel_details_03_tb: "",
	tel_details_04_tb: "",
	tel_details_05_tb: "",
	tel_details_06_tb: "",
	tel_details_07_tb: "",
	tel_details_08_tb: "",
	tel_details_09_tb: "",
	tel_details_10_tb: "",
	tel_details_11_tb: "",
	tel_details_12_tb: "",
	tel_details_13_tb: "",
	tel_details_14_tb: "",
	tel_details_15_tb: "",
	tel_details_16_tb: "",
	tel_details_17_tb: "",
	tel_details_18_tb: "",
	tel_details_19_tb: "",
	tel_details_20_tb: "",
	tel_details_21_tb: "",
	tel_details_22_tb: "",
	tel_details_23_tb: "",
	tel_details_24_tb: "",
	tel_property_tb: "",
	tel_reserve_tb: "",
	telmnglog_tb: "",
	template_tb: "",
	trend_01_tb: "",
	trend_02_tb: "",
	trend_03_tb: "",
	trend_04_tb: "",
	trend_05_tb: "",
	trend_06_tb: "",
	trend_07_tb: "",
	trend_08_tb: "",
	trend_09_tb: "",
	trend_10_tb: "",
	trend_11_tb: "",
	trend_12_tb: "",
	trend_13_tb: "",
	trend_14_tb: "",
	trend_15_tb: "",
	trend_16_tb: "",
	trend_17_tb: "",
	trend_18_tb: "",
	trend_19_tb: "",
	trend_20_tb: "",
	trend_21_tb: "",
	trend_22_tb: "",
	trend_23_tb: "",
	trend_24_tb: "",
	user_info_tb: "",
	user_info_rel_tb: "",
	yuyu_telno_01_tb: "",
	yuyu_telno_02_tb: "",
	yuyu_telno_03_tb: "",
	yuyu_telno_04_tb: "",
	yuyu_telno_05_tb: "",
	yuyu_telno_06_tb: "",
	yuyu_telno_07_tb: "",
	yuyu_telno_08_tb: "",
	yuyu_telno_09_tb: "",
	yuyu_telno_10_tb: "",
	yuyu_telno_11_tb: "",
	yuyu_telno_12_tb: "",
	card_asp_charge_tb: "",
	card_bill_01_tb: "",
	card_bill_02_tb: "",
	card_bill_03_tb: "",
	card_bill_04_tb: "",
	card_bill_05_tb: "",
	card_bill_06_tb: "",
	card_bill_07_tb: "",
	card_bill_08_tb: "",
	card_bill_09_tb: "",
	card_bill_10_tb: "",
	card_bill_11_tb: "",
	card_bill_12_tb: "",
	card_bill_13_tb: "",
	card_bill_14_tb: "",
	card_bill_15_tb: "",
	card_bill_16_tb: "",
	card_bill_17_tb: "",
	card_bill_18_tb: "",
	card_bill_19_tb: "",
	card_bill_20_tb: "",
	card_bill_21_tb: "",
	card_bill_22_tb: "",
	card_bill_23_tb: "",
	card_bill_24_tb: "",
	card_bill_history_tb: "",
	card_bill_master_tb: "",
	card_calc_state_tb: "",
	card_details_01_tb: "",
	card_details_02_tb: "",
	card_details_03_tb: "",
	card_details_04_tb: "",
	card_details_05_tb: "",
	card_details_06_tb: "",
	card_details_07_tb: "",
	card_details_08_tb: "",
	card_details_09_tb: "",
	card_details_10_tb: "",
	card_details_11_tb: "",
	card_details_12_tb: "",
	card_details_13_tb: "",
	card_details_14_tb: "",
	card_details_15_tb: "",
	card_details_16_tb: "",
	card_details_17_tb: "",
	card_details_18_tb: "",
	card_details_19_tb: "",
	card_details_20_tb: "",
	card_details_21_tb: "",
	card_details_22_tb: "",
	card_details_23_tb: "",
	card_details_24_tb: "",
	card_kamoku_tb: "",
	card_kamoku_rel_utiwake_tb: "",
	card_post_bill_01_tb: "",
	card_post_bill_02_tb: "",
	card_post_bill_03_tb: "",
	card_post_bill_04_tb: "",
	card_post_bill_05_tb: "",
	card_post_bill_06_tb: "",
	card_post_bill_07_tb: "",
	card_post_bill_08_tb: "",
	card_post_bill_09_tb: "",
	card_post_bill_10_tb: "",
	card_post_bill_11_tb: "",
	card_post_bill_12_tb: "",
	card_post_bill_13_tb: "",
	card_post_bill_14_tb: "",
	card_post_bill_15_tb: "",
	card_post_bill_16_tb: "",
	card_post_bill_17_tb: "",
	card_post_bill_18_tb: "",
	card_post_bill_19_tb: "",
	card_post_bill_20_tb: "",
	card_post_bill_21_tb: "",
	card_post_bill_22_tb: "",
	card_post_bill_23_tb: "",
	card_post_bill_24_tb: "",
	card_property_tb: "",
	card_usehistory_01_tb: "",
	card_usehistory_02_tb: "",
	card_usehistory_03_tb: "",
	card_usehistory_04_tb: "",
	card_usehistory_05_tb: "",
	card_usehistory_06_tb: "",
	card_usehistory_07_tb: "",
	card_usehistory_08_tb: "",
	card_usehistory_09_tb: "",
	card_usehistory_10_tb: "",
	card_usehistory_11_tb: "",
	card_usehistory_12_tb: "",
	cardmnglog_tb: "",
	card_01_tb: "",
	card_02_tb: "",
	card_03_tb: "",
	card_04_tb: "",
	card_05_tb: "",
	card_06_tb: "",
	card_07_tb: "",
	card_08_tb: "",
	card_09_tb: "",
	card_10_tb: "",
	card_11_tb: "",
	card_12_tb: "",
	card_13_tb: "",
	card_14_tb: "",
	card_15_tb: "",
	card_16_tb: "",
	card_17_tb: "",
	card_18_tb: "",
	card_19_tb: "",
	card_20_tb: "",
	card_21_tb: "",
	card_22_tb: "",
	card_23_tb: "",
	card_24_tb: "",
	card_tb: "",
	purchase_bill_01_tb: "",
	purchase_bill_02_tb: "",
	purchase_bill_03_tb: "",
	purchase_bill_04_tb: "",
	purchase_bill_05_tb: "",
	purchase_bill_06_tb: "",
	purchase_bill_07_tb: "",
	purchase_bill_08_tb: "",
	purchase_bill_09_tb: "",
	purchase_bill_10_tb: "",
	purchase_bill_11_tb: "",
	purchase_bill_12_tb: "",
	purchase_bill_13_tb: "",
	purchase_bill_14_tb: "",
	purchase_bill_15_tb: "",
	purchase_bill_16_tb: "",
	purchase_bill_17_tb: "",
	purchase_bill_18_tb: "",
	purchase_bill_19_tb: "",
	purchase_bill_20_tb: "",
	purchase_bill_21_tb: "",
	purchase_bill_22_tb: "",
	purchase_bill_23_tb: "",
	purchase_bill_24_tb: "",
	purchase_history_tb: "",
	purchase_details_01_tb: "",
	purchase_details_02_tb: "",
	purchase_details_03_tb: "",
	purchase_details_04_tb: "",
	purchase_details_05_tb: "",
	purchase_details_06_tb: "",
	purchase_details_07_tb: "",
	purchase_details_08_tb: "",
	purchase_details_09_tb: "",
	purchase_details_10_tb: "",
	purchase_details_11_tb: "",
	purchase_details_12_tb: "",
	purchase_details_13_tb: "",
	purchase_details_14_tb: "",
	purchase_details_15_tb: "",
	purchase_details_16_tb: "",
	purchase_details_17_tb: "",
	purchase_details_18_tb: "",
	purchase_details_19_tb: "",
	purchase_details_20_tb: "",
	purchase_details_21_tb: "",
	purchase_details_22_tb: "",
	purchase_details_23_tb: "",
	purchase_details_24_tb: "",
	purchase_kamoku_tb: "",
	purchase_kamoku_rel_utiwake_tb: "",
	purchase_post_bill_01_tb: "",
	purchase_post_bill_02_tb: "",
	purchase_post_bill_03_tb: "",
	purchase_post_bill_04_tb: "",
	purchase_post_bill_05_tb: "",
	purchase_post_bill_06_tb: "",
	purchase_post_bill_07_tb: "",
	purchase_post_bill_08_tb: "",
	purchase_post_bill_09_tb: "",
	purchase_post_bill_10_tb: "",
	purchase_post_bill_11_tb: "",
	purchase_post_bill_12_tb: "",
	purchase_post_bill_13_tb: "",
	purchase_post_bill_14_tb: "",
	purchase_post_bill_15_tb: "",
	purchase_post_bill_16_tb: "",
	purchase_post_bill_17_tb: "",
	purchase_post_bill_18_tb: "",
	purchase_post_bill_19_tb: "",
	purchase_post_bill_20_tb: "",
	purchase_post_bill_21_tb: "",
	purchase_post_bill_22_tb: "",
	purchase_post_bill_23_tb: "",
	purchase_post_bill_24_tb: "",
	purchase_tb: "",
	purchase_01_tb: "",
	purchase_02_tb: "",
	purchase_03_tb: "",
	purchase_04_tb: "",
	purchase_05_tb: "",
	purchase_06_tb: "",
	purchase_07_tb: "",
	purchase_08_tb: "",
	purchase_09_tb: "",
	purchase_10_tb: "",
	purchase_11_tb: "",
	purchase_12_tb: "",
	purchase_13_tb: "",
	purchase_14_tb: "",
	purchase_15_tb: "",
	purchase_16_tb: "",
	purchase_17_tb: "",
	purchase_18_tb: "",
	purchase_19_tb: "",
	purchase_20_tb: "",
	purchase_21_tb: "",
	purchase_22_tb: "",
	purchase_23_tb: "",
	purchase_24_tb: "",
	post_property_tb: "",
	change_post_tb: "",
	order_tb: "",
	order_teldetail_tb: "where orderid in (select orderid from order_tb where pactid = " + PACTID + ");",
	order_history_tb: "where orderid in (select orderid from order_tb where pactid = " + PACTID + ");",
	transfer_tb: "where orderid in (select orderid from order_tb where pactid = " + PACTID + ");",
	actlog_tb: "",
	adjust_utiwake_tb: "",
	assets_tb: "",
	assets_01_tb: "",
	assets_02_tb: "",
	assets_03_tb: "",
	assets_04_tb: "",
	assets_05_tb: "",
	assets_06_tb: "",
	assets_07_tb: "",
	assets_08_tb: "",
	assets_09_tb: "",
	assets_10_tb: "",
	assets_11_tb: "",
	assets_12_tb: "",
	assets_13_tb: "",
	assets_14_tb: "",
	assets_15_tb: "",
	assets_16_tb: "",
	assets_17_tb: "",
	assets_18_tb: "",
	assets_19_tb: "",
	assets_20_tb: "",
	assets_21_tb: "",
	assets_22_tb: "",
	assets_23_tb: "",
	assets_24_tb: "",
	assets_reserve_tb: "",
	assets_type_tb: "",
	copy_asp_charge_tb: "",
	copy_bill_01_tb: "",
	copy_bill_02_tb: "",
	copy_bill_03_tb: "",
	copy_bill_04_tb: "",
	copy_bill_05_tb: "",
	copy_bill_06_tb: "",
	copy_bill_07_tb: "",
	copy_bill_08_tb: "",
	copy_bill_09_tb: "",
	copy_bill_10_tb: "",
	copy_bill_11_tb: "",
	copy_bill_12_tb: "",
	copy_bill_13_tb: "",
	copy_bill_14_tb: "",
	copy_bill_15_tb: "",
	copy_bill_16_tb: "",
	copy_bill_17_tb: "",
	copy_bill_18_tb: "",
	copy_bill_19_tb: "",
	copy_bill_20_tb: "",
	copy_bill_21_tb: "",
	copy_bill_22_tb: "",
	copy_bill_23_tb: "",
	copy_bill_24_tb: "",
	copy_details_01_tb: "",
	copy_details_02_tb: "",
	copy_details_03_tb: "",
	copy_details_04_tb: "",
	copy_details_05_tb: "",
	copy_details_06_tb: "",
	copy_details_07_tb: "",
	copy_details_08_tb: "",
	copy_details_09_tb: "",
	copy_details_10_tb: "",
	copy_details_11_tb: "",
	copy_details_12_tb: "",
	copy_details_13_tb: "",
	copy_details_14_tb: "",
	copy_details_15_tb: "",
	copy_details_16_tb: "",
	copy_details_17_tb: "",
	copy_details_18_tb: "",
	copy_details_19_tb: "",
	copy_details_20_tb: "",
	copy_details_21_tb: "",
	copy_details_22_tb: "",
	copy_details_23_tb: "",
	copy_details_24_tb: "",
	copy_history_tb: "",
	copy_history_01_tb: "",
	copy_history_02_tb: "",
	copy_history_03_tb: "",
	copy_history_04_tb: "",
	copy_history_05_tb: "",
	copy_history_06_tb: "",
	copy_history_07_tb: "",
	copy_history_08_tb: "",
	copy_history_09_tb: "",
	copy_history_10_tb: "",
	copy_history_11_tb: "",
	copy_history_12_tb: "",
	copy_kamoku_tb: "",
	copy_kamoku_rel_utiwake_tb: "",
	copy_post_bill_01_tb: "",
	copy_post_bill_02_tb: "",
	copy_post_bill_03_tb: "",
	copy_post_bill_04_tb: "",
	copy_post_bill_05_tb: "",
	copy_post_bill_06_tb: "",
	copy_post_bill_07_tb: "",
	copy_post_bill_08_tb: "",
	copy_post_bill_09_tb: "",
	copy_post_bill_10_tb: "",
	copy_post_bill_11_tb: "",
	copy_post_bill_12_tb: "",
	copy_post_bill_13_tb: "",
	copy_post_bill_14_tb: "",
	copy_post_bill_15_tb: "",
	copy_post_bill_16_tb: "",
	copy_post_bill_17_tb: "",
	copy_post_bill_18_tb: "",
	copy_post_bill_19_tb: "",
	copy_post_bill_20_tb: "",
	copy_post_bill_21_tb: "",
	copy_post_bill_22_tb: "",
	copy_post_bill_23_tb: "",
	copy_post_bill_24_tb: "",
	copy_tb: "",
	copy_01_tb: "",
	copy_02_tb: "",
	copy_03_tb: "",
	copy_04_tb: "",
	copy_05_tb: "",
	copy_06_tb: "",
	copy_07_tb: "",
	copy_08_tb: "",
	copy_09_tb: "",
	copy_10_tb: "",
	copy_11_tb: "",
	copy_12_tb: "",
	copy_13_tb: "",
	copy_14_tb: "",
	copy_15_tb: "",
	copy_16_tb: "",
	copy_17_tb: "",
	copy_18_tb: "",
	copy_19_tb: "",
	copy_20_tb: "",
	copy_21_tb: "",
	copy_22_tb: "",
	copy_23_tb: "",
	copy_24_tb: "",
	dl_pattern_tb: "",
	dl_column_tb: "where dlid in (select dlid from dl_pattern_tb where pactid = " + PACTID + ");",
	faq_rel_pact_tb: "",
	favorite_usermenu_tb: "",
	inquiry_tb: "",
	joker_member_rel_pact_tb: "",
	management_log_tb: "",
	management_property_tb: "",
	mt_order_regist_tel_tb: "",
	mt_order_tb: "",
	mt_template_tb: "",
	mt_order_teldetail_tb: "where orderid in (select orderid from mt_order_tb where pactid = " + PACTID + ");",
	mt_order_history_tb: "where orderid in (select orderid from mt_order_tb where pactid = " + PACTID + ");",
	mt_transfer_tb: "where orderid in (select orderid from mt_order_tb where pactid = " + PACTID + ");",
	mt_order_sub_tb: "where orderid in (select orderid from mt_order_tb where pactid = " + PACTID + ");",
	pact_except_tb: "",
	post_rel_shop_info_tb: "",
	price_relation_tb: "",
	purchase_asp_charge_tb: "",
	shipto_tb: "",
	shop_joker_log_tb: "",
	sim_index_tb: "",
	sshx_limit_tb: "",
	sshx_n0_tb: "",
	sshx_n1_tb: "",
	sshx_n10_tb: "",
	sshx_n2_tb: "",
	sshx_n3_tb: "",
	sshx_n4_tb: "",
	sshx_n5_tb: "",
	sshx_n6_tb: "",
	sshx_n7_tb: "",
	sshx_n8_tb: "",
	sshx_n9_tb: "",
	summary_bill_01_tb: "",
	summary_bill_02_tb: "",
	summary_bill_03_tb: "",
	summary_bill_04_tb: "",
	summary_bill_05_tb: "",
	summary_bill_06_tb: "",
	summary_bill_07_tb: "",
	summary_bill_08_tb: "",
	summary_bill_09_tb: "",
	summary_bill_10_tb: "",
	summary_bill_11_tb: "",
	summary_bill_12_tb: "",
	summary_bill_13_tb: "",
	summary_bill_14_tb: "",
	summary_bill_15_tb: "",
	summary_bill_16_tb: "",
	summary_bill_17_tb: "",
	summary_bill_18_tb: "",
	summary_bill_19_tb: "",
	summary_bill_20_tb: "",
	summary_bill_21_tb: "",
	summary_bill_22_tb: "",
	summary_bill_23_tb: "",
	summary_bill_24_tb: "",
	summary_formula_tb: "",
	summary_tel_bill_01_tb: "",
	summary_tel_bill_02_tb: "",
	summary_tel_bill_03_tb: "",
	summary_tel_bill_04_tb: "",
	summary_tel_bill_05_tb: "",
	summary_tel_bill_06_tb: "",
	summary_tel_bill_07_tb: "",
	summary_tel_bill_08_tb: "",
	summary_tel_bill_09_tb: "",
	summary_tel_bill_10_tb: "",
	summary_tel_bill_11_tb: "",
	summary_tel_bill_12_tb: "",
	summary_tel_bill_13_tb: "",
	summary_tel_bill_14_tb: "",
	summary_tel_bill_15_tb: "",
	summary_tel_bill_16_tb: "",
	summary_tel_bill_17_tb: "",
	summary_tel_bill_18_tb: "",
	summary_tel_bill_19_tb: "",
	summary_tel_bill_20_tb: "",
	summary_tel_bill_21_tb: "",
	summary_tel_bill_22_tb: "",
	summary_tel_bill_23_tb: "",
	summary_tel_bill_24_tb: "",
	tel_rel_assets_reserve_tb: "",
	tel_rel_assets_tb: "",
	tel_rel_assets_01_tb: "",
	tel_rel_assets_02_tb: "",
	tel_rel_assets_03_tb: "",
	tel_rel_assets_04_tb: "",
	tel_rel_assets_05_tb: "",
	tel_rel_assets_06_tb: "",
	tel_rel_assets_07_tb: "",
	tel_rel_assets_08_tb: "",
	tel_rel_assets_09_tb: "",
	tel_rel_assets_10_tb: "",
	tel_rel_assets_11_tb: "",
	tel_rel_assets_12_tb: "",
	tel_rel_assets_13_tb: "",
	tel_rel_assets_14_tb: "",
	tel_rel_assets_15_tb: "",
	tel_rel_assets_16_tb: "",
	tel_rel_assets_17_tb: "",
	tel_rel_assets_18_tb: "",
	tel_rel_assets_19_tb: "",
	tel_rel_assets_20_tb: "",
	tel_rel_assets_21_tb: "",
	tel_rel_assets_22_tb: "",
	tel_rel_assets_23_tb: "",
	tel_rel_assets_24_tb: "",
	tel_rel_tel_reserve_tb: "",
	tel_rel_tel_tb: "",
	tel_rel_tel_01_tb: "",
	tel_rel_tel_02_tb: "",
	tel_rel_tel_03_tb: "",
	tel_rel_tel_04_tb: "",
	tel_rel_tel_05_tb: "",
	tel_rel_tel_06_tb: "",
	tel_rel_tel_07_tb: "",
	tel_rel_tel_08_tb: "",
	tel_rel_tel_09_tb: "",
	tel_rel_tel_10_tb: "",
	tel_rel_tel_11_tb: "",
	tel_rel_tel_12_tb: "",
	tel_rel_tel_13_tb: "",
	tel_rel_tel_14_tb: "",
	tel_rel_tel_15_tb: "",
	tel_rel_tel_16_tb: "",
	tel_rel_tel_17_tb: "",
	tel_rel_tel_18_tb: "",
	tel_rel_tel_19_tb: "",
	tel_rel_tel_20_tb: "",
	tel_rel_tel_21_tb: "",
	tel_rel_tel_22_tb: "",
	tel_rel_tel_23_tb: "",
	tel_rel_tel_24_tb: "",
	tweak_config_tb: "",
	tweak_point_tb: ""
};
var A_delete = ["delete from tel_rel_assets_reserve_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_01_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_02_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_03_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_04_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_05_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_06_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_07_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_08_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_09_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_10_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_11_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_12_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_13_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_14_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_15_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_16_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_17_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_18_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_19_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_20_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_21_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_22_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_23_tb where pactid = " + PACTID + ";", "delete from tel_rel_assets_24_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_reserve_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_01_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_02_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_03_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_04_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_05_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_06_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_07_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_08_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_09_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_10_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_11_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_12_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_13_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_14_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_15_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_16_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_17_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_18_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_19_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_20_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_21_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_22_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_23_tb where pactid = " + PACTID + ";", "delete from tel_rel_tel_24_tb where pactid = " + PACTID + ";", "delete from actlog_tb where pactid = " + PACTID + ";", "delete from adjust_utiwake_tb where pactid = " + PACTID + ";", "delete from assets_tb where pactid = " + PACTID + ";", "delete from assets_01_tb where pactid = " + PACTID + ";", "delete from assets_02_tb where pactid = " + PACTID + ";", "delete from assets_03_tb where pactid = " + PACTID + ";", "delete from assets_04_tb where pactid = " + PACTID + ";", "delete from assets_05_tb where pactid = " + PACTID + ";", "delete from assets_06_tb where pactid = " + PACTID + ";", "delete from assets_07_tb where pactid = " + PACTID + ";", "delete from assets_08_tb where pactid = " + PACTID + ";", "delete from assets_09_tb where pactid = " + PACTID + ";", "delete from assets_10_tb where pactid = " + PACTID + ";", "delete from assets_11_tb where pactid = " + PACTID + ";", "delete from assets_12_tb where pactid = " + PACTID + ";", "delete from assets_13_tb where pactid = " + PACTID + ";", "delete from assets_14_tb where pactid = " + PACTID + ";", "delete from assets_15_tb where pactid = " + PACTID + ";", "delete from assets_16_tb where pactid = " + PACTID + ";", "delete from assets_17_tb where pactid = " + PACTID + ";", "delete from assets_18_tb where pactid = " + PACTID + ";", "delete from assets_19_tb where pactid = " + PACTID + ";", "delete from assets_20_tb where pactid = " + PACTID + ";", "delete from assets_21_tb where pactid = " + PACTID + ";", "delete from assets_22_tb where pactid = " + PACTID + ";", "delete from assets_23_tb where pactid = " + PACTID + ";", "delete from assets_24_tb where pactid = " + PACTID + ";", "delete from assets_reserve_tb where pactid = " + PACTID + ";", "delete from assets_type_tb where pactid = " + PACTID + ";", "delete from copy_asp_charge_tb where pactid = " + PACTID + ";", "delete from copy_bill_01_tb where pactid = " + PACTID + ";", "delete from copy_bill_02_tb where pactid = " + PACTID + ";", "delete from copy_bill_03_tb where pactid = " + PACTID + ";", "delete from copy_bill_04_tb where pactid = " + PACTID + ";", "delete from copy_bill_05_tb where pactid = " + PACTID + ";", "delete from copy_bill_06_tb where pactid = " + PACTID + ";", "delete from copy_bill_07_tb where pactid = " + PACTID + ";", "delete from copy_bill_08_tb where pactid = " + PACTID + ";", "delete from copy_bill_09_tb where pactid = " + PACTID + ";", "delete from copy_bill_10_tb where pactid = " + PACTID + ";", "delete from copy_bill_11_tb where pactid = " + PACTID + ";", "delete from copy_bill_12_tb where pactid = " + PACTID + ";", "delete from copy_bill_13_tb where pactid = " + PACTID + ";", "delete from copy_bill_14_tb where pactid = " + PACTID + ";", "delete from copy_bill_15_tb where pactid = " + PACTID + ";", "delete from copy_bill_16_tb where pactid = " + PACTID + ";", "delete from copy_bill_17_tb where pactid = " + PACTID + ";", "delete from copy_bill_18_tb where pactid = " + PACTID + ";", "delete from copy_bill_19_tb where pactid = " + PACTID + ";", "delete from copy_bill_20_tb where pactid = " + PACTID + ";", "delete from copy_bill_21_tb where pactid = " + PACTID + ";", "delete from copy_bill_22_tb where pactid = " + PACTID + ";", "delete from copy_bill_23_tb where pactid = " + PACTID + ";", "delete from copy_bill_24_tb where pactid = " + PACTID + ";", "delete from copy_details_01_tb where pactid = " + PACTID + ";", "delete from copy_details_02_tb where pactid = " + PACTID + ";", "delete from copy_details_03_tb where pactid = " + PACTID + ";", "delete from copy_details_04_tb where pactid = " + PACTID + ";", "delete from copy_details_05_tb where pactid = " + PACTID + ";", "delete from copy_details_06_tb where pactid = " + PACTID + ";", "delete from copy_details_07_tb where pactid = " + PACTID + ";", "delete from copy_details_08_tb where pactid = " + PACTID + ";", "delete from copy_details_09_tb where pactid = " + PACTID + ";", "delete from copy_details_10_tb where pactid = " + PACTID + ";", "delete from copy_details_11_tb where pactid = " + PACTID + ";", "delete from copy_details_12_tb where pactid = " + PACTID + ";", "delete from copy_details_13_tb where pactid = " + PACTID + ";", "delete from copy_details_14_tb where pactid = " + PACTID + ";", "delete from copy_details_15_tb where pactid = " + PACTID + ";", "delete from copy_details_16_tb where pactid = " + PACTID + ";", "delete from copy_details_17_tb where pactid = " + PACTID + ";", "delete from copy_details_18_tb where pactid = " + PACTID + ";", "delete from copy_details_19_tb where pactid = " + PACTID + ";", "delete from copy_details_20_tb where pactid = " + PACTID + ";", "delete from copy_details_21_tb where pactid = " + PACTID + ";", "delete from copy_details_22_tb where pactid = " + PACTID + ";", "delete from copy_details_23_tb where pactid = " + PACTID + ";", "delete from copy_details_24_tb where pactid = " + PACTID + ";", "delete from copy_history_tb where pactid = " + PACTID + ";", "delete from copy_history_01_tb where pactid = " + PACTID + ";", "delete from copy_history_02_tb where pactid = " + PACTID + ";", "delete from copy_history_03_tb where pactid = " + PACTID + ";", "delete from copy_history_04_tb where pactid = " + PACTID + ";", "delete from copy_history_05_tb where pactid = " + PACTID + ";", "delete from copy_history_06_tb where pactid = " + PACTID + ";", "delete from copy_history_07_tb where pactid = " + PACTID + ";", "delete from copy_history_08_tb where pactid = " + PACTID + ";", "delete from copy_history_09_tb where pactid = " + PACTID + ";", "delete from copy_history_10_tb where pactid = " + PACTID + ";", "delete from copy_history_11_tb where pactid = " + PACTID + ";", "delete from copy_history_12_tb where pactid = " + PACTID + ";", "delete from copy_kamoku_rel_utiwake_tb where pactid = " + PACTID + ";", "delete from copy_kamoku_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_01_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_02_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_03_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_04_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_05_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_06_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_07_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_08_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_09_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_10_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_11_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_12_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_13_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_14_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_15_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_16_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_17_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_18_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_19_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_20_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_21_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_22_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_23_tb where pactid = " + PACTID + ";", "delete from copy_post_bill_24_tb where pactid = " + PACTID + ";", "delete from copy_tb where pactid = " + PACTID + ";", "delete from copy_01_tb where pactid = " + PACTID + ";", "delete from copy_02_tb where pactid = " + PACTID + ";", "delete from copy_03_tb where pactid = " + PACTID + ";", "delete from copy_04_tb where pactid = " + PACTID + ";", "delete from copy_05_tb where pactid = " + PACTID + ";", "delete from copy_06_tb where pactid = " + PACTID + ";", "delete from copy_07_tb where pactid = " + PACTID + ";", "delete from copy_08_tb where pactid = " + PACTID + ";", "delete from copy_09_tb where pactid = " + PACTID + ";", "delete from copy_10_tb where pactid = " + PACTID + ";", "delete from copy_11_tb where pactid = " + PACTID + ";", "delete from copy_12_tb where pactid = " + PACTID + ";", "delete from copy_13_tb where pactid = " + PACTID + ";", "delete from copy_14_tb where pactid = " + PACTID + ";", "delete from copy_15_tb where pactid = " + PACTID + ";", "delete from copy_16_tb where pactid = " + PACTID + ";", "delete from copy_17_tb where pactid = " + PACTID + ";", "delete from copy_18_tb where pactid = " + PACTID + ";", "delete from copy_19_tb where pactid = " + PACTID + ";", "delete from copy_20_tb where pactid = " + PACTID + ";", "delete from copy_21_tb where pactid = " + PACTID + ";", "delete from copy_22_tb where pactid = " + PACTID + ";", "delete from copy_23_tb where pactid = " + PACTID + ";", "delete from copy_24_tb where pactid = " + PACTID + ";", "delete from dl_column_tb where dlid in (select dlid from dl_pattern_tb where pactid = " + PACTID + ");", "delete from dl_pattern_tb where pactid = " + PACTID + ";", "delete from faq_rel_pact_tb where pactid = " + PACTID + ";", "delete from favorite_usermenu_tb where pactid = " + PACTID + ";", "delete from inquiry_tb where pactid = " + PACTID + ";", "delete from joker_member_rel_pact_tb where pactid = " + PACTID + ";", "delete from management_log_tb where pactid = " + PACTID + ";", "delete from management_property_tb where pactid = " + PACTID + ";", "delete from mt_order_teldetail_tb where orderid in (select orderid from mt_order_tb where pactid = " + PACTID + ");", "delete from mt_order_history_tb where orderid in (select orderid from mt_order_tb where pactid = " + PACTID + ");", "delete from mt_transfer_tb where orderid in (select orderid from mt_order_tb where pactid = " + PACTID + ");", "delete from mt_order_sub_tb where orderid in (select orderid from mt_order_tb where pactid = " + PACTID + ");", "delete from mt_order_regist_tel_tb where pactid = " + PACTID + ";", "delete from mt_order_tb where pactid = " + PACTID + ";", "delete from mt_template_tb where pactid = " + PACTID + ";", "delete from pact_except_tb where pactid = " + PACTID + ";", "delete from post_rel_shop_info_tb where pactid = " + PACTID + ";", "delete from price_relation_tb where pactid = " + PACTID + ";", "delete from purchase_asp_charge_tb where pactid = " + PACTID + ";", "delete from shipto_tb where pactid = " + PACTID + ";", "delete from shop_joker_log_tb where pactid = " + PACTID + ";", "delete from sim_index_tb where pactid = " + PACTID + ";", "delete from sshx_limit_tb where pactid = " + PACTID + ";", "delete from sshx_n0_tb where pactid = " + PACTID + ";", "delete from sshx_n1_tb where pactid = " + PACTID + ";", "delete from sshx_n10_tb where pactid = " + PACTID + ";", "delete from sshx_n2_tb where pactid = " + PACTID + ";", "delete from sshx_n3_tb where pactid = " + PACTID + ";", "delete from sshx_n4_tb where pactid = " + PACTID + ";", "delete from sshx_n5_tb where pactid = " + PACTID + ";", "delete from sshx_n6_tb where pactid = " + PACTID + ";", "delete from sshx_n7_tb where pactid = " + PACTID + ";", "delete from sshx_n8_tb where pactid = " + PACTID + ";", "delete from sshx_n9_tb where pactid = " + PACTID + ";", "delete from summary_bill_01_tb where pactid = " + PACTID + ";", "delete from summary_bill_02_tb where pactid = " + PACTID + ";", "delete from summary_bill_03_tb where pactid = " + PACTID + ";", "delete from summary_bill_04_tb where pactid = " + PACTID + ";", "delete from summary_bill_05_tb where pactid = " + PACTID + ";", "delete from summary_bill_06_tb where pactid = " + PACTID + ";", "delete from summary_bill_07_tb where pactid = " + PACTID + ";", "delete from summary_bill_08_tb where pactid = " + PACTID + ";", "delete from summary_bill_09_tb where pactid = " + PACTID + ";", "delete from summary_bill_10_tb where pactid = " + PACTID + ";", "delete from summary_bill_11_tb where pactid = " + PACTID + ";", "delete from summary_bill_12_tb where pactid = " + PACTID + ";", "delete from summary_bill_13_tb where pactid = " + PACTID + ";", "delete from summary_bill_14_tb where pactid = " + PACTID + ";", "delete from summary_bill_15_tb where pactid = " + PACTID + ";", "delete from summary_bill_16_tb where pactid = " + PACTID + ";", "delete from summary_bill_17_tb where pactid = " + PACTID + ";", "delete from summary_bill_18_tb where pactid = " + PACTID + ";", "delete from summary_bill_19_tb where pactid = " + PACTID + ";", "delete from summary_bill_20_tb where pactid = " + PACTID + ";", "delete from summary_bill_21_tb where pactid = " + PACTID + ";", "delete from summary_bill_22_tb where pactid = " + PACTID + ";", "delete from summary_bill_23_tb where pactid = " + PACTID + ";", "delete from summary_bill_24_tb where pactid = " + PACTID + ";", "delete from summary_formula_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_01_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_02_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_03_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_04_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_05_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_06_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_07_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_08_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_09_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_10_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_11_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_12_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_13_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_14_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_15_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_16_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_17_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_18_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_19_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_20_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_21_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_22_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_23_tb where pactid = " + PACTID + ";", "delete from summary_tel_bill_24_tb where pactid = " + PACTID + ";", "delete from tweak_config_tb where pactid = " + PACTID + ";", "delete from tweak_point_tb where pactid = " + PACTID + ";", "delete from asp_charge_tb where pactid = " + PACTID + ";", "delete from bill_01_tb where pactid = " + PACTID + ";", "delete from bill_02_tb where pactid = " + PACTID + ";", "delete from bill_03_tb where pactid = " + PACTID + ";", "delete from bill_04_tb where pactid = " + PACTID + ";", "delete from bill_05_tb where pactid = " + PACTID + ";", "delete from bill_06_tb where pactid = " + PACTID + ";", "delete from bill_07_tb where pactid = " + PACTID + ";", "delete from bill_08_tb where pactid = " + PACTID + ";", "delete from bill_09_tb where pactid = " + PACTID + ";", "delete from bill_10_tb where pactid = " + PACTID + ";", "delete from bill_11_tb where pactid = " + PACTID + ";", "delete from bill_12_tb where pactid = " + PACTID + ";", "delete from bill_13_tb where pactid = " + PACTID + ";", "delete from bill_14_tb where pactid = " + PACTID + ";", "delete from bill_15_tb where pactid = " + PACTID + ";", "delete from bill_16_tb where pactid = " + PACTID + ";", "delete from bill_17_tb where pactid = " + PACTID + ";", "delete from bill_18_tb where pactid = " + PACTID + ";", "delete from bill_19_tb where pactid = " + PACTID + ";", "delete from bill_20_tb where pactid = " + PACTID + ";", "delete from bill_21_tb where pactid = " + PACTID + ";", "delete from bill_22_tb where pactid = " + PACTID + ";", "delete from bill_23_tb where pactid = " + PACTID + ";", "delete from bill_24_tb where pactid = " + PACTID + ";", "delete from bill_custom_tb where pactid = " + PACTID + ";", "delete from bill_history_tb where pactid = " + PACTID + ";", "delete from bill_prtel_tb where pactid = " + PACTID + ";", "delete from clamp_tb where pactid = " + PACTID + ";", "delete from clampfile_tb where pactid = " + PACTID + ";", "delete from clamptemp_tb where pactid = " + PACTID + ";", "delete from clampdb_error_tb where pactid = " + PACTID + ";", "delete from clampdb_index_tb where pactid = " + PACTID + ";", "delete from clampdb_type_tb where pactid = " + PACTID + ";", "delete from clampdb_ready_tb where pactid = " + PACTID + ";", "delete from commhistory_01_tb where pactid = " + PACTID + ";", "delete from commhistory_02_tb where pactid = " + PACTID + ";", "delete from commhistory_03_tb where pactid = " + PACTID + ";", "delete from commhistory_04_tb where pactid = " + PACTID + ";", "delete from commhistory_05_tb where pactid = " + PACTID + ";", "delete from commhistory_06_tb where pactid = " + PACTID + ";", "delete from commhistory_07_tb where pactid = " + PACTID + ";", "delete from commhistory_08_tb where pactid = " + PACTID + ";", "delete from commhistory_09_tb where pactid = " + PACTID + ";", "delete from commhistory_10_tb where pactid = " + PACTID + ";", "delete from commhistory_11_tb where pactid = " + PACTID + ";", "delete from commhistory_12_tb where pactid = " + PACTID + ";", "delete from disratio_tb where pactid = " + PACTID + ";", "delete from dl_property_tb where pactid = " + PACTID + ";", "delete from dummy_tel_tb where pactid = " + PACTID + ";", "delete from fnc_relation_tb where pactid = " + PACTID + ";", "delete from infohistory_01_tb where pactid = " + PACTID + ";", "delete from infohistory_02_tb where pactid = " + PACTID + ";", "delete from infohistory_03_tb where pactid = " + PACTID + ";", "delete from infohistory_04_tb where pactid = " + PACTID + ";", "delete from infohistory_05_tb where pactid = " + PACTID + ";", "delete from infohistory_06_tb where pactid = " + PACTID + ";", "delete from infohistory_07_tb where pactid = " + PACTID + ";", "delete from infohistory_08_tb where pactid = " + PACTID + ";", "delete from infohistory_09_tb where pactid = " + PACTID + ";", "delete from infohistory_10_tb where pactid = " + PACTID + ";", "delete from infohistory_11_tb where pactid = " + PACTID + ";", "delete from infohistory_12_tb where pactid = " + PACTID + ";", "delete from ip_restrict_tb where pactid = " + PACTID + ";", "delete from joker_log_tb where pactid = " + PACTID + ";", "delete from kamoku_rel_utiwake_tb where pactid = " + PACTID + ";", "delete from kamoku_tb where pactid = " + PACTID + ";", "delete from kousi_bill_01_tb where pactid = " + PACTID + ";", "delete from kousi_bill_02_tb where pactid = " + PACTID + ";", "delete from kousi_bill_03_tb where pactid = " + PACTID + ";", "delete from kousi_bill_04_tb where pactid = " + PACTID + ";", "delete from kousi_bill_05_tb where pactid = " + PACTID + ";", "delete from kousi_bill_06_tb where pactid = " + PACTID + ";", "delete from kousi_bill_07_tb where pactid = " + PACTID + ";", "delete from kousi_bill_08_tb where pactid = " + PACTID + ";", "delete from kousi_bill_09_tb where pactid = " + PACTID + ";", "delete from kousi_bill_10_tb where pactid = " + PACTID + ";", "delete from kousi_bill_11_tb where pactid = " + PACTID + ";", "delete from kousi_bill_12_tb where pactid = " + PACTID + ";", "delete from kousi_bill_13_tb where pactid = " + PACTID + ";", "delete from kousi_bill_14_tb where pactid = " + PACTID + ";", "delete from kousi_bill_15_tb where pactid = " + PACTID + ";", "delete from kousi_bill_16_tb where pactid = " + PACTID + ";", "delete from kousi_bill_17_tb where pactid = " + PACTID + ";", "delete from kousi_bill_18_tb where pactid = " + PACTID + ";", "delete from kousi_bill_19_tb where pactid = " + PACTID + ";", "delete from kousi_bill_20_tb where pactid = " + PACTID + ";", "delete from kousi_bill_21_tb where pactid = " + PACTID + ";", "delete from kousi_bill_22_tb where pactid = " + PACTID + ";", "delete from kousi_bill_23_tb where pactid = " + PACTID + ";", "delete from kousi_bill_24_tb where pactid = " + PACTID + ";", "delete from kousi_default_tb where pactid = " + PACTID + ";", "delete from kousi_fromtel_master_tb where pactid = " + PACTID + ";", "delete from kousi_rel_pact_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_01_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_02_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_03_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_04_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_05_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_06_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_07_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_08_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_09_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_10_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_11_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_12_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_13_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_14_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_15_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_16_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_17_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_18_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_19_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_20_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_21_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_22_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_23_tb where pactid = " + PACTID + ";", "delete from kousi_tel_bill_24_tb where pactid = " + PACTID + ";", "delete from kousi_totel_master_tb where pactid = " + PACTID + ";", "delete from login_rel_sess_tb where pactid = " + PACTID + ";", "delete from mnglog_tb where pactid = " + PACTID + ";", "delete from pact_rel_carrier_tb where pactid = " + PACTID + ";", "delete from pact_rel_shop_tb where pactid = " + PACTID + ";", "delete from plan_history_tb where pactid = " + PACTID + ";", "delete from plan_predata_tb where pactid = " + PACTID + ";", "delete from plan_recom_tb where pactid = " + PACTID + ";", "delete from recent_telcnt_tb where pactid = " + PACTID + ";", "delete from recog_batch_tb where pactid = " + PACTID + ";", "delete from recognize_tb where pactid = " + PACTID + ";", "delete from secure_charge_tb where pactid = " + PACTID + ";", "delete from secure_history_tb where pactid = " + PACTID + ";", "delete from secure_pact_tb where pactid = " + PACTID + ";", "delete from secure_reserve_tb where pactid = " + PACTID + ";", "delete from secure_tb where pactid = " + PACTID + ";", "delete from shop_relation_tb where pactid = " + PACTID + ";", "delete from sim_config_tb where pactid = " + PACTID + ";", "delete from sim_log_tb where pactid = " + PACTID + ";", "delete from sim_top_telno_01_tb where pactid = " + PACTID + ";", "delete from sim_top_telno_02_tb where pactid = " + PACTID + ";", "delete from sim_top_telno_03_tb where pactid = " + PACTID + ";", "delete from sim_top_telno_04_tb where pactid = " + PACTID + ";", "delete from sim_top_telno_05_tb where pactid = " + PACTID + ";", "delete from sim_top_telno_06_tb where pactid = " + PACTID + ";", "delete from sim_top_telno_07_tb where pactid = " + PACTID + ";", "delete from sim_top_telno_08_tb where pactid = " + PACTID + ";", "delete from sim_top_telno_09_tb where pactid = " + PACTID + ";", "delete from sim_top_telno_10_tb where pactid = " + PACTID + ";", "delete from sim_top_telno_11_tb where pactid = " + PACTID + ";", "delete from sim_top_telno_12_tb where pactid = " + PACTID + ";", "delete from sim_trend_01_tb where pactid = " + PACTID + ";", "delete from sim_trend_02_tb where pactid = " + PACTID + ";", "delete from sim_trend_03_tb where pactid = " + PACTID + ";", "delete from sim_trend_04_tb where pactid = " + PACTID + ";", "delete from sim_trend_05_tb where pactid = " + PACTID + ";", "delete from sim_trend_06_tb where pactid = " + PACTID + ";", "delete from sim_trend_07_tb where pactid = " + PACTID + ";", "delete from sim_trend_08_tb where pactid = " + PACTID + ";", "delete from sim_trend_09_tb where pactid = " + PACTID + ";", "delete from sim_trend_10_tb where pactid = " + PACTID + ";", "delete from sim_trend_11_tb where pactid = " + PACTID + ";", "delete from sim_trend_12_tb where pactid = " + PACTID + ";", "delete from sim_trend_13_tb where pactid = " + PACTID + ";", "delete from sim_trend_14_tb where pactid = " + PACTID + ";", "delete from sim_trend_15_tb where pactid = " + PACTID + ";", "delete from sim_trend_16_tb where pactid = " + PACTID + ";", "delete from sim_trend_17_tb where pactid = " + PACTID + ";", "delete from sim_trend_18_tb where pactid = " + PACTID + ";", "delete from sim_trend_19_tb where pactid = " + PACTID + ";", "delete from sim_trend_20_tb where pactid = " + PACTID + ";", "delete from sim_trend_21_tb where pactid = " + PACTID + ";", "delete from sim_trend_22_tb where pactid = " + PACTID + ";", "delete from sim_trend_23_tb where pactid = " + PACTID + ";", "delete from sim_trend_24_tb where pactid = " + PACTID + ";", "delete from sshx_a1_tb where pactid = " + PACTID + ";", "delete from sshx_a2_tb where pactid = " + PACTID + ";", "delete from sshx_b1_tb where pactid = " + PACTID + ";", "delete from sshx_b2_tb where pactid = " + PACTID + ";", "delete from sshx_b3_tb where pactid = " + PACTID + ";", "delete from sshx_b4_tb where pactid = " + PACTID + ";", "delete from sshx_c1_tb where pactid = " + PACTID + ";", "delete from sshx_c2_tb where pactid = " + PACTID + ";", "delete from sshx_c3_tb where pactid = " + PACTID + ";", "delete from sshx_c4_tb where pactid = " + PACTID + ";", "delete from sshx_d1_tb where pactid = " + PACTID + ";", "delete from sshx_d2_tb where pactid = " + PACTID + ";", "delete from sshx_d3_tb where pactid = " + PACTID + ";", "delete from sshx_d4_tb where pactid = " + PACTID + ";", "delete from sshx_d5_tb where pactid = " + PACTID + ";", "delete from sshx_e1_tb where pactid = " + PACTID + ";", "delete from sshx_inpmark_tb where pactid = " + PACTID + ";", "delete from sshx_j1_tb where pactid = " + PACTID + ";", "delete from sshx_j2_tb where pactid = " + PACTID + ";", "delete from sshx_j3_tb where pactid = " + PACTID + ";", "delete from sshx_j4_tb where pactid = " + PACTID + ";", "delete from sshx_tel_01_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_02_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_03_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_04_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_05_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_06_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_07_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_08_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_09_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_10_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_11_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_12_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_13_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_14_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_15_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_16_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_17_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_18_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_19_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_20_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_21_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_22_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_23_bkup where pactid = " + PACTID + ";", "delete from sshx_tel_24_bkup where pactid = " + PACTID + ";", "delete from sshx_zzz_01_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_02_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_03_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_04_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_05_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_06_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_07_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_08_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_09_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_10_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_11_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_12_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_13_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_14_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_15_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_16_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_17_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_18_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_19_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_20_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_21_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_22_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_23_tb where pactid = " + PACTID + ";", "delete from sshx_zzz_24_tb where pactid = " + PACTID + ";", "delete from tel_bill_01_tb where pactid = " + PACTID + ";", "delete from tel_bill_02_tb where pactid = " + PACTID + ";", "delete from tel_bill_03_tb where pactid = " + PACTID + ";", "delete from tel_bill_04_tb where pactid = " + PACTID + ";", "delete from tel_bill_05_tb where pactid = " + PACTID + ";", "delete from tel_bill_06_tb where pactid = " + PACTID + ";", "delete from tel_bill_07_tb where pactid = " + PACTID + ";", "delete from tel_bill_08_tb where pactid = " + PACTID + ";", "delete from tel_bill_09_tb where pactid = " + PACTID + ";", "delete from tel_bill_10_tb where pactid = " + PACTID + ";", "delete from tel_bill_11_tb where pactid = " + PACTID + ";", "delete from tel_bill_12_tb where pactid = " + PACTID + ";", "delete from tel_bill_13_tb where pactid = " + PACTID + ";", "delete from tel_bill_14_tb where pactid = " + PACTID + ";", "delete from tel_bill_15_tb where pactid = " + PACTID + ";", "delete from tel_bill_16_tb where pactid = " + PACTID + ";", "delete from tel_bill_17_tb where pactid = " + PACTID + ";", "delete from tel_bill_18_tb where pactid = " + PACTID + ";", "delete from tel_bill_19_tb where pactid = " + PACTID + ";", "delete from tel_bill_20_tb where pactid = " + PACTID + ";", "delete from tel_bill_21_tb where pactid = " + PACTID + ";", "delete from tel_bill_22_tb where pactid = " + PACTID + ";", "delete from tel_bill_23_tb where pactid = " + PACTID + ";", "delete from tel_bill_24_tb where pactid = " + PACTID + ";", "delete from tel_details_01_tb where pactid = " + PACTID + ";", "delete from tel_details_02_tb where pactid = " + PACTID + ";", "delete from tel_details_03_tb where pactid = " + PACTID + ";", "delete from tel_details_04_tb where pactid = " + PACTID + ";", "delete from tel_details_05_tb where pactid = " + PACTID + ";", "delete from tel_details_06_tb where pactid = " + PACTID + ";", "delete from tel_details_07_tb where pactid = " + PACTID + ";", "delete from tel_details_08_tb where pactid = " + PACTID + ";", "delete from tel_details_09_tb where pactid = " + PACTID + ";", "delete from tel_details_10_tb where pactid = " + PACTID + ";", "delete from tel_details_11_tb where pactid = " + PACTID + ";", "delete from tel_details_12_tb where pactid = " + PACTID + ";", "delete from tel_details_13_tb where pactid = " + PACTID + ";", "delete from tel_details_14_tb where pactid = " + PACTID + ";", "delete from tel_details_15_tb where pactid = " + PACTID + ";", "delete from tel_details_16_tb where pactid = " + PACTID + ";", "delete from tel_details_17_tb where pactid = " + PACTID + ";", "delete from tel_details_18_tb where pactid = " + PACTID + ";", "delete from tel_details_19_tb where pactid = " + PACTID + ";", "delete from tel_details_20_tb where pactid = " + PACTID + ";", "delete from tel_details_21_tb where pactid = " + PACTID + ";", "delete from tel_details_22_tb where pactid = " + PACTID + ";", "delete from tel_details_23_tb where pactid = " + PACTID + ";", "delete from tel_details_24_tb where pactid = " + PACTID + ";", "delete from tel_property_tb where pactid = " + PACTID + ";", "delete from tel_reserve_tb where pactid = " + PACTID + ";", "delete from telmnglog_tb where pactid = " + PACTID + ";", "delete from template_tb where pactid = " + PACTID + ";", "delete from trend_01_tb where pactid = " + PACTID + ";", "delete from trend_02_tb where pactid = " + PACTID + ";", "delete from trend_03_tb where pactid = " + PACTID + ";", "delete from trend_04_tb where pactid = " + PACTID + ";", "delete from trend_05_tb where pactid = " + PACTID + ";", "delete from trend_06_tb where pactid = " + PACTID + ";", "delete from trend_07_tb where pactid = " + PACTID + ";", "delete from trend_08_tb where pactid = " + PACTID + ";", "delete from trend_09_tb where pactid = " + PACTID + ";", "delete from trend_10_tb where pactid = " + PACTID + ";", "delete from trend_11_tb where pactid = " + PACTID + ";", "delete from trend_12_tb where pactid = " + PACTID + ";", "delete from trend_13_tb where pactid = " + PACTID + ";", "delete from trend_14_tb where pactid = " + PACTID + ";", "delete from trend_15_tb where pactid = " + PACTID + ";", "delete from trend_16_tb where pactid = " + PACTID + ";", "delete from trend_17_tb where pactid = " + PACTID + ";", "delete from trend_18_tb where pactid = " + PACTID + ";", "delete from trend_19_tb where pactid = " + PACTID + ";", "delete from trend_20_tb where pactid = " + PACTID + ";", "delete from trend_21_tb where pactid = " + PACTID + ";", "delete from trend_22_tb where pactid = " + PACTID + ";", "delete from trend_23_tb where pactid = " + PACTID + ";", "delete from trend_24_tb where pactid = " + PACTID + ";", "delete from user_info_rel_tb where pactid = " + PACTID + ";", "delete from user_info_tb where pactid = " + PACTID + ";", "delete from user_tb where pactid = " + PACTID + ";", "delete from user_deleted_tb where pactid = " + PACTID + ";", "delete from yuyu_telno_01_tb where pactid = " + PACTID + ";", "delete from yuyu_telno_02_tb where pactid = " + PACTID + ";", "delete from yuyu_telno_03_tb where pactid = " + PACTID + ";", "delete from yuyu_telno_04_tb where pactid = " + PACTID + ";", "delete from yuyu_telno_05_tb where pactid = " + PACTID + ";", "delete from yuyu_telno_06_tb where pactid = " + PACTID + ";", "delete from yuyu_telno_07_tb where pactid = " + PACTID + ";", "delete from yuyu_telno_08_tb where pactid = " + PACTID + ";", "delete from yuyu_telno_09_tb where pactid = " + PACTID + ";", "delete from yuyu_telno_10_tb where pactid = " + PACTID + ";", "delete from yuyu_telno_11_tb where pactid = " + PACTID + ";", "delete from yuyu_telno_12_tb where pactid = " + PACTID + ";", "delete from tel_01_tb where pactid = " + PACTID + ";", "delete from tel_02_tb where pactid = " + PACTID + ";", "delete from tel_03_tb where pactid = " + PACTID + ";", "delete from tel_04_tb where pactid = " + PACTID + ";", "delete from tel_05_tb where pactid = " + PACTID + ";", "delete from tel_06_tb where pactid = " + PACTID + ";", "delete from tel_07_tb where pactid = " + PACTID + ";", "delete from tel_08_tb where pactid = " + PACTID + ";", "delete from tel_09_tb where pactid = " + PACTID + ";", "delete from tel_10_tb where pactid = " + PACTID + ";", "delete from tel_11_tb where pactid = " + PACTID + ";", "delete from tel_12_tb where pactid = " + PACTID + ";", "delete from tel_13_tb where pactid = " + PACTID + ";", "delete from tel_14_tb where pactid = " + PACTID + ";", "delete from tel_15_tb where pactid = " + PACTID + ";", "delete from tel_16_tb where pactid = " + PACTID + ";", "delete from tel_17_tb where pactid = " + PACTID + ";", "delete from tel_18_tb where pactid = " + PACTID + ";", "delete from tel_19_tb where pactid = " + PACTID + ";", "delete from tel_20_tb where pactid = " + PACTID + ";", "delete from tel_21_tb where pactid = " + PACTID + ";", "delete from tel_22_tb where pactid = " + PACTID + ";", "delete from tel_23_tb where pactid = " + PACTID + ";", "delete from tel_24_tb where pactid = " + PACTID + ";", "delete from tel_tb where pactid = " + PACTID + ";", "delete from tel_deleted_tb where pactid = " + PACTID + ";", "delete from card_asp_charge_tb where pactid = " + PACTID + ";", "delete from card_bill_01_tb where pactid = " + PACTID + ";", "delete from card_bill_02_tb where pactid = " + PACTID + ";", "delete from card_bill_03_tb where pactid = " + PACTID + ";", "delete from card_bill_04_tb where pactid = " + PACTID + ";", "delete from card_bill_05_tb where pactid = " + PACTID + ";", "delete from card_bill_06_tb where pactid = " + PACTID + ";", "delete from card_bill_07_tb where pactid = " + PACTID + ";", "delete from card_bill_08_tb where pactid = " + PACTID + ";", "delete from card_bill_09_tb where pactid = " + PACTID + ";", "delete from card_bill_10_tb where pactid = " + PACTID + ";", "delete from card_bill_11_tb where pactid = " + PACTID + ";", "delete from card_bill_12_tb where pactid = " + PACTID + ";", "delete from card_bill_13_tb where pactid = " + PACTID + ";", "delete from card_bill_14_tb where pactid = " + PACTID + ";", "delete from card_bill_15_tb where pactid = " + PACTID + ";", "delete from card_bill_16_tb where pactid = " + PACTID + ";", "delete from card_bill_17_tb where pactid = " + PACTID + ";", "delete from card_bill_18_tb where pactid = " + PACTID + ";", "delete from card_bill_19_tb where pactid = " + PACTID + ";", "delete from card_bill_20_tb where pactid = " + PACTID + ";", "delete from card_bill_21_tb where pactid = " + PACTID + ";", "delete from card_bill_22_tb where pactid = " + PACTID + ";", "delete from card_bill_23_tb where pactid = " + PACTID + ";", "delete from card_bill_24_tb where pactid = " + PACTID + ";", "delete from card_bill_history_tb where pactid = " + PACTID + ";", "delete from card_bill_master_tb where pactid = " + PACTID + ";", "delete from card_calc_state_tb where pactid = " + PACTID + ";", "delete from card_details_01_tb where pactid = " + PACTID + ";", "delete from card_details_02_tb where pactid = " + PACTID + ";", "delete from card_details_03_tb where pactid = " + PACTID + ";", "delete from card_details_04_tb where pactid = " + PACTID + ";", "delete from card_details_05_tb where pactid = " + PACTID + ";", "delete from card_details_06_tb where pactid = " + PACTID + ";", "delete from card_details_07_tb where pactid = " + PACTID + ";", "delete from card_details_08_tb where pactid = " + PACTID + ";", "delete from card_details_09_tb where pactid = " + PACTID + ";", "delete from card_details_10_tb where pactid = " + PACTID + ";", "delete from card_details_11_tb where pactid = " + PACTID + ";", "delete from card_details_12_tb where pactid = " + PACTID + ";", "delete from card_details_13_tb where pactid = " + PACTID + ";", "delete from card_details_14_tb where pactid = " + PACTID + ";", "delete from card_details_15_tb where pactid = " + PACTID + ";", "delete from card_details_16_tb where pactid = " + PACTID + ";", "delete from card_details_17_tb where pactid = " + PACTID + ";", "delete from card_details_18_tb where pactid = " + PACTID + ";", "delete from card_details_19_tb where pactid = " + PACTID + ";", "delete from card_details_20_tb where pactid = " + PACTID + ";", "delete from card_details_21_tb where pactid = " + PACTID + ";", "delete from card_details_22_tb where pactid = " + PACTID + ";", "delete from card_details_23_tb where pactid = " + PACTID + ";", "delete from card_details_24_tb where pactid = " + PACTID + ";", "delete from card_kamoku_rel_utiwake_tb where pactid = " + PACTID + ";", "delete from card_kamoku_tb where pactid = " + PACTID + ";", "delete from card_post_bill_01_tb where pactid = " + PACTID + ";", "delete from card_post_bill_02_tb where pactid = " + PACTID + ";", "delete from card_post_bill_03_tb where pactid = " + PACTID + ";", "delete from card_post_bill_04_tb where pactid = " + PACTID + ";", "delete from card_post_bill_05_tb where pactid = " + PACTID + ";", "delete from card_post_bill_06_tb where pactid = " + PACTID + ";", "delete from card_post_bill_07_tb where pactid = " + PACTID + ";", "delete from card_post_bill_08_tb where pactid = " + PACTID + ";", "delete from card_post_bill_09_tb where pactid = " + PACTID + ";", "delete from card_post_bill_10_tb where pactid = " + PACTID + ";", "delete from card_post_bill_11_tb where pactid = " + PACTID + ";", "delete from card_post_bill_12_tb where pactid = " + PACTID + ";", "delete from card_post_bill_13_tb where pactid = " + PACTID + ";", "delete from card_post_bill_14_tb where pactid = " + PACTID + ";", "delete from card_post_bill_15_tb where pactid = " + PACTID + ";", "delete from card_post_bill_16_tb where pactid = " + PACTID + ";", "delete from card_post_bill_17_tb where pactid = " + PACTID + ";", "delete from card_post_bill_18_tb where pactid = " + PACTID + ";", "delete from card_post_bill_19_tb where pactid = " + PACTID + ";", "delete from card_post_bill_20_tb where pactid = " + PACTID + ";", "delete from card_post_bill_21_tb where pactid = " + PACTID + ";", "delete from card_post_bill_22_tb where pactid = " + PACTID + ";", "delete from card_post_bill_23_tb where pactid = " + PACTID + ";", "delete from card_post_bill_24_tb where pactid = " + PACTID + ";", "delete from card_property_tb where pactid = " + PACTID + ";", "delete from card_usehistory_01_tb where pactid = " + PACTID + ";", "delete from card_usehistory_02_tb where pactid = " + PACTID + ";", "delete from card_usehistory_03_tb where pactid = " + PACTID + ";", "delete from card_usehistory_04_tb where pactid = " + PACTID + ";", "delete from card_usehistory_05_tb where pactid = " + PACTID + ";", "delete from card_usehistory_06_tb where pactid = " + PACTID + ";", "delete from card_usehistory_07_tb where pactid = " + PACTID + ";", "delete from card_usehistory_08_tb where pactid = " + PACTID + ";", "delete from card_usehistory_09_tb where pactid = " + PACTID + ";", "delete from card_usehistory_10_tb where pactid = " + PACTID + ";", "delete from card_usehistory_11_tb where pactid = " + PACTID + ";", "delete from card_usehistory_12_tb where pactid = " + PACTID + ";", "delete from cardmnglog_tb where pactid = " + PACTID + ";", "delete from card_01_tb where pactid = " + PACTID + ";", "delete from card_02_tb where pactid = " + PACTID + ";", "delete from card_03_tb where pactid = " + PACTID + ";", "delete from card_04_tb where pactid = " + PACTID + ";", "delete from card_05_tb where pactid = " + PACTID + ";", "delete from card_06_tb where pactid = " + PACTID + ";", "delete from card_07_tb where pactid = " + PACTID + ";", "delete from card_08_tb where pactid = " + PACTID + ";", "delete from card_09_tb where pactid = " + PACTID + ";", "delete from card_10_tb where pactid = " + PACTID + ";", "delete from card_11_tb where pactid = " + PACTID + ";", "delete from card_12_tb where pactid = " + PACTID + ";", "delete from card_13_tb where pactid = " + PACTID + ";", "delete from card_14_tb where pactid = " + PACTID + ";", "delete from card_15_tb where pactid = " + PACTID + ";", "delete from card_16_tb where pactid = " + PACTID + ";", "delete from card_17_tb where pactid = " + PACTID + ";", "delete from card_18_tb where pactid = " + PACTID + ";", "delete from card_19_tb where pactid = " + PACTID + ";", "delete from card_20_tb where pactid = " + PACTID + ";", "delete from card_21_tb where pactid = " + PACTID + ";", "delete from card_22_tb where pactid = " + PACTID + ";", "delete from card_23_tb where pactid = " + PACTID + ";", "delete from card_24_tb where pactid = " + PACTID + ";", "delete from card_tb where pactid = " + PACTID + ";", "delete from purchase_bill_01_tb where pactid = " + PACTID + ";", "delete from purchase_bill_02_tb where pactid = " + PACTID + ";", "delete from purchase_bill_03_tb where pactid = " + PACTID + ";", "delete from purchase_bill_04_tb where pactid = " + PACTID + ";", "delete from purchase_bill_05_tb where pactid = " + PACTID + ";", "delete from purchase_bill_06_tb where pactid = " + PACTID + ";", "delete from purchase_bill_07_tb where pactid = " + PACTID + ";", "delete from purchase_bill_08_tb where pactid = " + PACTID + ";", "delete from purchase_bill_09_tb where pactid = " + PACTID + ";", "delete from purchase_bill_10_tb where pactid = " + PACTID + ";", "delete from purchase_bill_11_tb where pactid = " + PACTID + ";", "delete from purchase_bill_12_tb where pactid = " + PACTID + ";", "delete from purchase_bill_13_tb where pactid = " + PACTID + ";", "delete from purchase_bill_14_tb where pactid = " + PACTID + ";", "delete from purchase_bill_15_tb where pactid = " + PACTID + ";", "delete from purchase_bill_16_tb where pactid = " + PACTID + ";", "delete from purchase_bill_17_tb where pactid = " + PACTID + ";", "delete from purchase_bill_18_tb where pactid = " + PACTID + ";", "delete from purchase_bill_19_tb where pactid = " + PACTID + ";", "delete from purchase_bill_20_tb where pactid = " + PACTID + ";", "delete from purchase_bill_21_tb where pactid = " + PACTID + ";", "delete from purchase_bill_22_tb where pactid = " + PACTID + ";", "delete from purchase_bill_23_tb where pactid = " + PACTID + ";", "delete from purchase_bill_24_tb where pactid = " + PACTID + ";", "delete from purchase_history_tb where pactid = " + PACTID + ";", "delete from purchase_details_01_tb where pactid = " + PACTID + ";", "delete from purchase_details_02_tb where pactid = " + PACTID + ";", "delete from purchase_details_03_tb where pactid = " + PACTID + ";", "delete from purchase_details_04_tb where pactid = " + PACTID + ";", "delete from purchase_details_05_tb where pactid = " + PACTID + ";", "delete from purchase_details_06_tb where pactid = " + PACTID + ";", "delete from purchase_details_07_tb where pactid = " + PACTID + ";", "delete from purchase_details_08_tb where pactid = " + PACTID + ";", "delete from purchase_details_09_tb where pactid = " + PACTID + ";", "delete from purchase_details_10_tb where pactid = " + PACTID + ";", "delete from purchase_details_11_tb where pactid = " + PACTID + ";", "delete from purchase_details_12_tb where pactid = " + PACTID + ";", "delete from purchase_details_13_tb where pactid = " + PACTID + ";", "delete from purchase_details_14_tb where pactid = " + PACTID + ";", "delete from purchase_details_15_tb where pactid = " + PACTID + ";", "delete from purchase_details_16_tb where pactid = " + PACTID + ";", "delete from purchase_details_17_tb where pactid = " + PACTID + ";", "delete from purchase_details_18_tb where pactid = " + PACTID + ";", "delete from purchase_details_19_tb where pactid = " + PACTID + ";", "delete from purchase_details_20_tb where pactid = " + PACTID + ";", "delete from purchase_details_21_tb where pactid = " + PACTID + ";", "delete from purchase_details_22_tb where pactid = " + PACTID + ";", "delete from purchase_details_23_tb where pactid = " + PACTID + ";", "delete from purchase_details_24_tb where pactid = " + PACTID + ";", "delete from purchase_kamoku_tb where pactid = " + PACTID + ";", "delete from purchase_kamoku_rel_utiwake_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_01_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_02_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_03_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_04_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_05_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_06_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_07_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_08_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_09_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_10_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_11_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_12_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_13_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_14_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_15_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_16_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_17_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_18_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_19_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_20_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_21_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_22_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_23_tb where pactid = " + PACTID + ";", "delete from purchase_post_bill_24_tb where pactid = " + PACTID + ";", "delete from purchase_tb where pactid = " + PACTID + ";", "delete from purchase_01_tb where pactid = " + PACTID + ";", "delete from purchase_02_tb where pactid = " + PACTID + ";", "delete from purchase_03_tb where pactid = " + PACTID + ";", "delete from purchase_04_tb where pactid = " + PACTID + ";", "delete from purchase_05_tb where pactid = " + PACTID + ";", "delete from purchase_06_tb where pactid = " + PACTID + ";", "delete from purchase_07_tb where pactid = " + PACTID + ";", "delete from purchase_08_tb where pactid = " + PACTID + ";", "delete from purchase_09_tb where pactid = " + PACTID + ";", "delete from purchase_10_tb where pactid = " + PACTID + ";", "delete from purchase_11_tb where pactid = " + PACTID + ";", "delete from purchase_12_tb where pactid = " + PACTID + ";", "delete from purchase_13_tb where pactid = " + PACTID + ";", "delete from purchase_14_tb where pactid = " + PACTID + ";", "delete from purchase_15_tb where pactid = " + PACTID + ";", "delete from purchase_16_tb where pactid = " + PACTID + ";", "delete from purchase_17_tb where pactid = " + PACTID + ";", "delete from purchase_18_tb where pactid = " + PACTID + ";", "delete from purchase_19_tb where pactid = " + PACTID + ";", "delete from purchase_20_tb where pactid = " + PACTID + ";", "delete from purchase_21_tb where pactid = " + PACTID + ";", "delete from purchase_22_tb where pactid = " + PACTID + ";", "delete from purchase_23_tb where pactid = " + PACTID + ";", "delete from purchase_24_tb where pactid = " + PACTID + ";", "delete from post_property_tb where pactid = " + PACTID + ";", "delete from post_relation_01_tb where pactid = " + PACTID + ";", "delete from post_relation_02_tb where pactid = " + PACTID + ";", "delete from post_relation_03_tb where pactid = " + PACTID + ";", "delete from post_relation_04_tb where pactid = " + PACTID + ";", "delete from post_relation_05_tb where pactid = " + PACTID + ";", "delete from post_relation_06_tb where pactid = " + PACTID + ";", "delete from post_relation_07_tb where pactid = " + PACTID + ";", "delete from post_relation_08_tb where pactid = " + PACTID + ";", "delete from post_relation_09_tb where pactid = " + PACTID + ";", "delete from post_relation_10_tb where pactid = " + PACTID + ";", "delete from post_relation_11_tb where pactid = " + PACTID + ";", "delete from post_relation_12_tb where pactid = " + PACTID + ";", "delete from post_relation_13_tb where pactid = " + PACTID + ";", "delete from post_relation_14_tb where pactid = " + PACTID + ";", "delete from post_relation_15_tb where pactid = " + PACTID + ";", "delete from post_relation_16_tb where pactid = " + PACTID + ";", "delete from post_relation_17_tb where pactid = " + PACTID + ";", "delete from post_relation_18_tb where pactid = " + PACTID + ";", "delete from post_relation_19_tb where pactid = " + PACTID + ";", "delete from post_relation_20_tb where pactid = " + PACTID + ";", "delete from post_relation_21_tb where pactid = " + PACTID + ";", "delete from post_relation_22_tb where pactid = " + PACTID + ";", "delete from post_relation_23_tb where pactid = " + PACTID + ";", "delete from post_relation_24_tb where pactid = " + PACTID + ";", "delete from post_relation_tb where pactid = " + PACTID + ";", "delete from post_relation_deleted_tb where pactid = " + PACTID + ";", "delete from post_01_tb where pactid = " + PACTID + ";", "delete from post_02_tb where pactid = " + PACTID + ";", "delete from post_03_tb where pactid = " + PACTID + ";", "delete from post_04_tb where pactid = " + PACTID + ";", "delete from post_05_tb where pactid = " + PACTID + ";", "delete from post_06_tb where pactid = " + PACTID + ";", "delete from post_07_tb where pactid = " + PACTID + ";", "delete from post_08_tb where pactid = " + PACTID + ";", "delete from post_09_tb where pactid = " + PACTID + ";", "delete from post_10_tb where pactid = " + PACTID + ";", "delete from post_11_tb where pactid = " + PACTID + ";", "delete from post_12_tb where pactid = " + PACTID + ";", "delete from post_13_tb where pactid = " + PACTID + ";", "delete from post_14_tb where pactid = " + PACTID + ";", "delete from post_15_tb where pactid = " + PACTID + ";", "delete from post_16_tb where pactid = " + PACTID + ";", "delete from post_17_tb where pactid = " + PACTID + ";", "delete from post_18_tb where pactid = " + PACTID + ";", "delete from post_19_tb where pactid = " + PACTID + ";", "delete from post_20_tb where pactid = " + PACTID + ";", "delete from post_21_tb where pactid = " + PACTID + ";", "delete from post_22_tb where pactid = " + PACTID + ";", "delete from post_23_tb where pactid = " + PACTID + ";", "delete from post_24_tb where pactid = " + PACTID + ";", "delete from order_teldetail_tb where orderid in (select orderid from order_tb where pactid = " + PACTID + ");", "delete from order_history_tb where orderid in (select orderid from order_tb where pactid = " + PACTID + ");", "delete from transfer_tb where orderid in (select orderid from order_tb where pactid = " + PACTID + ");", "delete from order_tb where pactid = " + PACTID + ";", "delete from post_tb where pactid = " + PACTID + ";", "delete from post_deleted_tb where pactid = " + PACTID + ";", "delete from change_post_tb where pactid = " + PACTID + ";", "delete from pact_tb where pactid = " + PACTID + ";"];
var fp_out = fopen("/kcs/script/batch/pactdata-" + PACTID + ".sql", "w+");
fwrite(fp_out, "SET client_encoding = 'UTF8';\n");

for (var sql of Object.values(A_delete)) //ファイル出力
{
	fwrite(fp_out, sql + "\n");
}

var dbh = pg_connect("host=" + HOST + " port=5432 dbname=" + DBNAME + " user=web password=" + dbPassW);
pg_query(dbh, "SET client_encoding = 'UTF-8'");
var fp_pass = fopen("/home/web/.pgpass", "w+");
fwrite(fp_pass, "*:*:*:*:" + dbPassP);
fclose(fp_pass);
exec("/bin/chmod 600 /home/web/.pgpass");

for (var key in H_select) //pg_dump用に一時テーブルを作成
//テーブル特有のwhere句がある場合はそのwhere句を追加
//稼働中ＤＢポート確認
//pgpool起動時
//pg_dumpでデータ出力
//データ出力ファイルを読み込み
//データファイル削除
//一時テーブルを削除
{
	var value = H_select[key];
	var sql = "/* pgpool\u7528 */select * into tmp_" + key + " from " + key + " ";

	if (value != "") //テーブル特有のwhere句がない場合はpactidを指定
		{
			sql += value;
		} else {
		sql += "where pactid = " + PACTID;
	}

	pg_query(dbh, sql);

	if (file_exists("/tmp/.s.PGSQL.6543") == true) {
		var dbPort = 6543;
	} else {
		dbPort = 5432;
	}

	exec("/usr/local/pgsql/bin/pg_dump -p " + dbPort + " -at tmp_" + key + " -U postgres -E UTF8 " + DBNAME + " > " + TEMPFILE);
	var A_line = Array();
	A_line = file(TEMPFILE);
	var cnt_line = A_line.length;
	var output_flg = false;

	for (var line of Object.values(A_line)) //copy文修正
	{
		if (preg_match("/^COPY/", line) == true) {
			fwrite(fp_out, "copy " + key + " from STDIN;\n");
			output_flg = true;
			continue;
		} else if (preg_match("/^\\\\.$/", line) == true) //ＣＯＰＹ文終了コード出力
			{
				fwrite(fp_out, "\\.\n");
				output_flg = false;
			}

		if (output_flg == true) {
			fwrite(fp_out, line);
		}
	}

	exec("/bin/rm -f " + TEMPFILE);
	sql = "drop table tmp_" + key;
	pg_query(dbh, sql);
	print(key + " done\n");
}

exec("/bin/rm -f /home/web/.pgpass");
fflush(fp_out);
fclose(fp_out);
throw die();

function usage() {
	print("\nUsage) " + SCRIPTNAME + " PACTID\n\n");
	throw die(1);
};